services:
  baza-podataka:
    image: postgres:17.5-alpine
    container_name: baza-podataka
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: operacijski-sustavi
    ports:
      - "5433:5432"
    networks:
      - shared-net
      
networks:
  shared-net:
    name: shared-net